releaseImage:
  repository: ''
  digest: ''
runtimeConfig: {}
sync:
  enabled: false
  mongoSecret:
    name: ''
    key: url
  mongoTlsSecret:
    name: ''
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi
