releaseImage:
  repository: ''
  digest: ''
runtimeConfig: {}
inputs:
  migrationConnection:
    name: ''
    key: migration-connection.json
    revision: ''
release:
  activeDeadlineSeconds: 300
  backoffLimit: 0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
powersync:
  enabled: false
  sourceSecret:
    name: ''
    key: uri
    revision: ''
  storageSecret:
    name: ''
    key: uri
    revision: ''
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi
