apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quizmon.configName" . }}
  labels:
    {{- include "quizmon.labels" . | nindent 4 }}
immutable: true
data:
  release-config.json: {{ .Values.runtimeConfig | toJson | quote }}
  operation.json: {{ include "quizmon.operation" . | quote }}
