/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/wrangler.dev.jsonc --include-runtime=false --env-interface=AccountEnv server/env.d.ts` (hash: ae797ad4f73851163a5f36216eb33175)
interface __BaseEnv_AccountEnv {
  EMAIL: SendEmail;
  AUTH_RATE_LIMIT: RateLimit;
  API_RATE_LIMIT: RateLimit;
  SYNC_URL: 'http://127.0.0.1:8089';
  SYNC_AUDIENCE: 'quizmon';
  AUTH_ORIGIN: 'http://localhost:4188';
  MAIL_DELIVERY: 'cloudflare' | 'test-mailbox';
  MAIL_FROM: '';
  BETTER_AUTH_SECRET: string;
  MONGO_URL: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface CloudflareEnv {
    EMAIL: SendEmail;
    AUTH_RATE_LIMIT: RateLimit;
    API_RATE_LIMIT: RateLimit;
    SYNC_URL: 'http://127.0.0.1:8089';
    SYNC_AUDIENCE: 'quizmon';
    AUTH_ORIGIN: 'http://localhost:4188';
    MAIL_DELIVERY: 'cloudflare';
    MAIL_FROM: '';
    BETTER_AUTH_SECRET: string;
    MONGO_URL: string;
  }
  interface Env extends __BaseEnv_AccountEnv {}
}
interface AccountEnv extends __BaseEnv_AccountEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'SYNC_URL'
      | 'SYNC_AUDIENCE'
      | 'AUTH_ORIGIN'
      | 'MAIL_DELIVERY'
      | 'MAIL_FROM'
      | 'BETTER_AUTH_SECRET'
      | 'MONGO_URL'
    >
  > {}
}
