/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/wrangler.dev.jsonc --include-runtime=false --env-interface=AccountEnv server/env.d.ts` (hash: f9436f6ea47854fde63083505a21e5f3)
interface __BaseEnv_AccountEnv {
  ACCOUNT_DB: Hyperdrive;
  EMAIL: SendEmail;
  AUTH_RATE_LIMIT: RateLimit;
  API_RATE_LIMIT: RateLimit;
  POWERSYNC_URL: 'http://127.0.0.1:8089';
  POWERSYNC_AUDIENCE: 'quizmon';
  AUTH_ORIGIN: 'http://localhost:4188';
  MAIL_DELIVERY: 'cloudflare' | 'test-mailbox';
  MAIL_FROM: '';
  BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
  }
  interface CloudflareEnv {
    ACCOUNT_DB: Hyperdrive;
    EMAIL: SendEmail;
    AUTH_RATE_LIMIT: RateLimit;
    API_RATE_LIMIT: RateLimit;
    POWERSYNC_URL: 'http://127.0.0.1:8089';
    POWERSYNC_AUDIENCE: 'quizmon';
    AUTH_ORIGIN: 'http://localhost:4188';
    MAIL_DELIVERY: 'cloudflare';
    MAIL_FROM: '';
    BETTER_AUTH_SECRET: string;
  }
  interface Env extends __BaseEnv_AccountEnv {}
}
interface AccountEnv extends __BaseEnv_AccountEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'POWERSYNC_URL'
      | 'POWERSYNC_AUDIENCE'
      | 'AUTH_ORIGIN'
      | 'MAIL_DELIVERY'
      | 'MAIL_FROM'
      | 'BETTER_AUTH_SECRET'
    >
  > {}
}
