import { style } from '@vanilla-extract/css';

export const hallRecord = style({});
export const hallRecordGroup = style({});
export const hallRecordHonors = style({});
export const hallRecordMissing = style({});
export const hallRecordPortrait = style({});
export const hallRecordScore = style({});
export const hallRecordSignature = style({});
export const hallRecordSpriteFlipped = style({});
export const leagueChallenge = style({});
export const leagueGoldButton = style({});
export const leagueHall = style({});
export const leagueHallInduction = style({});
export const leagueHallActions = style({});
export const leagueHallEmpty = style({});
export const leagueHallHeader = style({});
export const leagueHallHistory = style({});
export const leagueHallNavigation = style({});
export const leagueHallNotice = style({});
export const leagueProgress = style({});
export const leagueProgressStage = style({});
export const leagueProgressStageComplete = style({});
export const leagueProgressStageCurrent = style({});
export const leagueTrophy = style({});
export const leagueTrophyLocked = style({});
export const leagueTrophyImage = style({});
export const leagueTrophyRays = style({});
