/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as AccountFriendsRouteImport } from './routes/account_.friends'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as TrainerBadgesRouteImport } from './routes/trainer_.badges'
import { Route as TrainerEditRouteImport } from './routes/trainer_.edit'
import { Route as TrainerPokedexRouteImport } from './routes/trainer_.pokedex'
import { Route as TrainerTitlesRouteImport } from './routes/trainer_.titles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFriendsRoute = AccountFriendsRouteImport.update({
  id: '/account_/friends',
  path: '/account/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerBadgesRoute = TrainerBadgesRouteImport.update({
  id: '/trainer_/badges',
  path: '/trainer/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerEditRoute = TrainerEditRouteImport.update({
  id: '/trainer_/edit',
  path: '/trainer/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerPokedexRoute = TrainerPokedexRouteImport.update({
  id: '/trainer_/pokedex',
  path: '/trainer/pokedex',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerTitlesRoute = TrainerTitlesRouteImport.update({
  id: '/trainer_/titles',
  path: '/trainer/titles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/league': typeof LeagueRoute
  '/rankings': typeof RankingsRoute
  '/trainer': typeof TrainerRoute
  '/account/friends': typeof AccountFriendsRoute
  '/players/$id': typeof PlayersIdRoute
  '/trainer/badges': typeof TrainerBadgesRoute
  '/trainer/edit': typeof TrainerEditRoute
  '/trainer/pokedex': typeof TrainerPokedexRoute
  '/trainer/titles': typeof TrainerTitlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/league': typeof LeagueRoute
  '/rankings': typeof RankingsRoute
  '/trainer': typeof TrainerRoute
  '/account/friends': typeof AccountFriendsRoute
  '/players/$id': typeof PlayersIdRoute
  '/trainer/badges': typeof TrainerBadgesRoute
  '/trainer/edit': typeof TrainerEditRoute
  '/trainer/pokedex': typeof TrainerPokedexRoute
  '/trainer/titles': typeof TrainerTitlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/league': typeof LeagueRoute
  '/rankings': typeof RankingsRoute
  '/trainer': typeof TrainerRoute
  '/account_/friends': typeof AccountFriendsRoute
  '/players/$id': typeof PlayersIdRoute
  '/trainer_/badges': typeof TrainerBadgesRoute
  '/trainer_/edit': typeof TrainerEditRoute
  '/trainer_/pokedex': typeof TrainerPokedexRoute
  '/trainer_/titles': typeof TrainerTitlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/league'
    | '/rankings'
    | '/trainer'
    | '/account/friends'
    | '/players/$id'
    | '/trainer/badges'
    | '/trainer/edit'
    | '/trainer/pokedex'
    | '/trainer/titles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/league'
    | '/rankings'
    | '/trainer'
    | '/account/friends'
    | '/players/$id'
    | '/trainer/badges'
    | '/trainer/edit'
    | '/trainer/pokedex'
    | '/trainer/titles'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/league'
    | '/rankings'
    | '/trainer'
    | '/account_/friends'
    | '/players/$id'
    | '/trainer_/badges'
    | '/trainer_/edit'
    | '/trainer_/pokedex'
    | '/trainer_/titles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LeagueRoute: typeof LeagueRoute
  RankingsRoute: typeof RankingsRoute
  TrainerRoute: typeof TrainerRoute
  AccountFriendsRoute: typeof AccountFriendsRoute
  PlayersIdRoute: typeof PlayersIdRoute
  TrainerBadgesRoute: typeof TrainerBadgesRoute
  TrainerEditRoute: typeof TrainerEditRoute
  TrainerPokedexRoute: typeof TrainerPokedexRoute
  TrainerTitlesRoute: typeof TrainerTitlesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/friends': {
      id: '/account_/friends'
      path: '/account/friends'
      fullPath: '/account/friends'
      preLoaderRoute: typeof AccountFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer_/badges': {
      id: '/trainer_/badges'
      path: '/trainer/badges'
      fullPath: '/trainer/badges'
      preLoaderRoute: typeof TrainerBadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer_/edit': {
      id: '/trainer_/edit'
      path: '/trainer/edit'
      fullPath: '/trainer/edit'
      preLoaderRoute: typeof TrainerEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer_/pokedex': {
      id: '/trainer_/pokedex'
      path: '/trainer/pokedex'
      fullPath: '/trainer/pokedex'
      preLoaderRoute: typeof TrainerPokedexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer_/titles': {
      id: '/trainer_/titles'
      path: '/trainer/titles'
      fullPath: '/trainer/titles'
      preLoaderRoute: typeof TrainerTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LeagueRoute: LeagueRoute,
  RankingsRoute: RankingsRoute,
  TrainerRoute: TrainerRoute,
  AccountFriendsRoute: AccountFriendsRoute,
  PlayersIdRoute: PlayersIdRoute,
  TrainerBadgesRoute: TrainerBadgesRoute,
  TrainerEditRoute: TrainerEditRoute,
  TrainerPokedexRoute: TrainerPokedexRoute,
  TrainerTitlesRoute: TrainerTitlesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
