/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as AccountFriendsRouteImport } from './routes/account.friends'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as TrainerBadgesRouteImport } from './routes/trainer.badges'
import { Route as TrainerEditRouteImport } from './routes/trainer.edit'
import { Route as TrainerPokedexRouteImport } from './routes/trainer.pokedex'
import { Route as TrainerTitlesRouteImport } from './routes/trainer.titles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFriendsRoute = AccountFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AccountRoute,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerBadgesRoute = TrainerBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerEditRoute = TrainerEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerPokedexRoute = TrainerPokedexRouteImport.update({
  id: '/pokedex',
  path: '/pokedex',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerTitlesRoute = TrainerTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => TrainerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/league': typeof LeagueRoute
  '/rankings': typeof RankingsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/account/friends': typeof AccountFriendsRoute
  '/players/$id': typeof PlayersIdRoute
  '/trainer/badges': typeof TrainerBadgesRoute
  '/trainer/edit': typeof TrainerEditRoute
  '/trainer/pokedex': typeof TrainerPokedexRoute
  '/trainer/titles': typeof TrainerTitlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/league': typeof LeagueRoute
  '/rankings': typeof RankingsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/account/friends': typeof AccountFriendsRoute
  '/players/$id': typeof PlayersIdRoute
  '/trainer/badges': typeof TrainerBadgesRoute
  '/trainer/edit': typeof TrainerEditRoute
  '/trainer/pokedex': typeof TrainerPokedexRoute
  '/trainer/titles': typeof TrainerTitlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/league': typeof LeagueRoute
  '/rankings': typeof RankingsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/account/friends': typeof AccountFriendsRoute
  '/players/$id': typeof PlayersIdRoute
  '/trainer/badges': typeof TrainerBadgesRoute
  '/trainer/edit': typeof TrainerEditRoute
  '/trainer/pokedex': typeof TrainerPokedexRoute
  '/trainer/titles': typeof TrainerTitlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/league'
    | '/rankings'
    | '/trainer'
    | '/account/friends'
    | '/players/$id'
    | '/trainer/badges'
    | '/trainer/edit'
    | '/trainer/pokedex'
    | '/trainer/titles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/league'
    | '/rankings'
    | '/trainer'
    | '/account/friends'
    | '/players/$id'
    | '/trainer/badges'
    | '/trainer/edit'
    | '/trainer/pokedex'
    | '/trainer/titles'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/league'
    | '/rankings'
    | '/trainer'
    | '/account/friends'
    | '/players/$id'
    | '/trainer/badges'
    | '/trainer/edit'
    | '/trainer/pokedex'
    | '/trainer/titles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  LeagueRoute: typeof LeagueRoute
  RankingsRoute: typeof RankingsRoute
  TrainerRoute: typeof TrainerRouteWithChildren
  PlayersIdRoute: typeof PlayersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/friends': {
      id: '/account/friends'
      path: '/friends'
      fullPath: '/account/friends'
      preLoaderRoute: typeof AccountFriendsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/badges': {
      id: '/trainer/badges'
      path: '/badges'
      fullPath: '/trainer/badges'
      preLoaderRoute: typeof TrainerBadgesRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/edit': {
      id: '/trainer/edit'
      path: '/edit'
      fullPath: '/trainer/edit'
      preLoaderRoute: typeof TrainerEditRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/pokedex': {
      id: '/trainer/pokedex'
      path: '/pokedex'
      fullPath: '/trainer/pokedex'
      preLoaderRoute: typeof TrainerPokedexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/titles': {
      id: '/trainer/titles'
      path: '/titles'
      fullPath: '/trainer/titles'
      preLoaderRoute: typeof TrainerTitlesRouteImport
      parentRoute: typeof TrainerRoute
    }
  }
}

interface AccountRouteChildren {
  AccountFriendsRoute: typeof AccountFriendsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountFriendsRoute: AccountFriendsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface TrainerRouteChildren {
  TrainerBadgesRoute: typeof TrainerBadgesRoute
  TrainerEditRoute: typeof TrainerEditRoute
  TrainerPokedexRoute: typeof TrainerPokedexRoute
  TrainerTitlesRoute: typeof TrainerTitlesRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerBadgesRoute: TrainerBadgesRoute,
  TrainerEditRoute: TrainerEditRoute,
  TrainerPokedexRoute: TrainerPokedexRoute,
  TrainerTitlesRoute: TrainerTitlesRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  LeagueRoute: LeagueRoute,
  RankingsRoute: RankingsRoute,
  TrainerRoute: TrainerRouteWithChildren,
  PlayersIdRoute: PlayersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
